"""add ticket source and voice_call_sessions

Revision ID: c78e93327925
Revises: 34903ab29078
Create Date: 2026-09-19 00:32:40.306585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c78e93327925'
down_revision: Union[str, None] = '34903ab29078'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Created explicitly: add_column() does not reliably emit CREATE TYPE the
    # way create_table() does, and existing tickets need a default to backfill.
    ticket_source = postgresql.ENUM(
        'WEB', 'PHONE', 'EMAIL', 'WALK_IN', name='ticket_source_enum'
    )
    ticket_source.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voice_call_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('twilio_call_sid', sa.String(length=64), nullable=False),
    sa.Column('from_number', sa.String(length=32), nullable=False),
    sa.Column('to_number', sa.String(length=32), nullable=False),
    sa.Column('state', sa.Enum('GREETING', 'COLLECT_DESCRIPTION', 'COLLECT_NAME', 'COLLECT_PHONE', 'COLLECT_EMAIL', 'CONFIRM_EMAIL', 'CONFIRM_CATEGORY', 'ANYTHING_ELSE', 'ESCALATED', 'COMPLETED', 'ABANDONED', name='voice_call_state_enum'), nullable=False),
    sa.Column('collected', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('turns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('misunderstanding_count', sa.SmallInteger(), nullable=False),
    sa.Column('email_attempt_count', sa.SmallInteger(), nullable=False),
    sa.Column('escalated', sa.Boolean(), nullable=False),
    sa.Column('escalation_reason', sa.Enum('CALLER_REQUESTED', 'REPEATED_MISUNDERSTANDING', 'SYSTEM_ERROR', name='escalation_reason_enum'), nullable=True),
    sa.Column('ticket_id', sa.UUID(), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_call_sessions_created_at'), 'voice_call_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_voice_call_sessions_ticket_id'), 'voice_call_sessions', ['ticket_id'], unique=False)
    op.create_index(op.f('ix_voice_call_sessions_twilio_call_sid'), 'voice_call_sessions', ['twilio_call_sid'], unique=True)
    op.add_column(
        'tickets',
        sa.Column(
            'source',
            postgresql.ENUM('WEB', 'PHONE', 'EMAIL', 'WALK_IN', name='ticket_source_enum', create_type=False),
            nullable=False,
            server_default='WEB',
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'source')
    op.drop_index(op.f('ix_voice_call_sessions_twilio_call_sid'), table_name='voice_call_sessions')
    op.drop_index(op.f('ix_voice_call_sessions_ticket_id'), table_name='voice_call_sessions')
    op.drop_index(op.f('ix_voice_call_sessions_created_at'), table_name='voice_call_sessions')
    op.drop_table('voice_call_sessions')
    # ### end Alembic commands ###
    op.execute('DROP TYPE IF EXISTS escalation_reason_enum')
    op.execute('DROP TYPE IF EXISTS voice_call_state_enum')
    op.execute('DROP TYPE IF EXISTS ticket_source_enum')
